[project]
name = "jetblue-route-calculate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["httpx>=0.28.1", "msgspec>=0.19.0"]
